version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5435:5432"
    volumes:
      - ./sql/table_migration.sql:/docker-entrypoint-initdb.d/table_migration.sql

  etl:
    build: .
    container_name: etl_container
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  postgres_data: